version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bank_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank-account
    ports:
      - "3307:3306"
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

#  rabbitmq:
#    image: rabbitmq:3-management
#    hostname: rabbitmq
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    networks:
#      - bank-network
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 5

#  configserver:
#    image: savindu29/configserver:v3
#    container_name: config-server
#    ports:
#      - "8071:8071"
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - bank-network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8071/actuator/health/readiness || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 60s


  account-management:
    image: savindu29/account:v3
    container_name: account-management
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      DB_NAME: bank-account
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SPRING_APPLICATION_NAME: account
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071/
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      mysql:
        condition: service_healthy
#      configserver:
#        condition: service_healthy
    networks:
      - bank-network
    command: /bin/sh -c "sleep 90 && java -jar /account-management-0.0.1-SNAPSHOT.jar"

  loan-management:
    image: savindu29/loan:v3
    container_name: loan-management
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      DB_NAME: bank-loan
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SPRING_APPLICATION_NAME: loan
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071/
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8093:8093"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      mysql:
        condition: service_healthy
#      configserver:
#        condition: service_healthy
    networks:
      - bank-network
    command: /bin/sh -c "sleep 90 && java -jar /loan-management-0.0.1-SNAPSHOT.jar"

  card-management:
    image: savindu29/card:v3
    container_name: card-management
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      DB_NAME: bank-card
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SPRING_APPLICATION_NAME: card
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071/
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8092:8092"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      mysql:
        condition: service_healthy
#      configserver:
#        condition: service_healthy
    networks:
      - bank-network
    command: /bin/sh -c "sleep 90 && java -jar /card-management-0.0.1-SNAPSHOT.jar"

networks:
  bank-network:
    driver: bridge
